[build]
base = "/"
publish = "public/"
command = "echo 'Build complete'"

[build.environment]
CYPRESS_CACHE_FOLDER = "./node_modules/CypressBinary"
TERM = "xterm"

[functions]
directory = "functions"

[context.dev]
environment = { NODE_ENV = "development", BASE_URL = "http://localhost:8888" }

[[redirects]]
from = "/spotify/id/*"
to = "/.netlify/functions/spotify-rss?id=:splat"

[[plugins]]
package = "netlify-plugin-cypress"
[plugins.inputs]
browser = "electron"
record = true
