[build]
base = "/"
publish = "public/"
command = "echo 'Build complete'"

[functions]
directory = "netlify/functions"

[[redirects]]
from = "/spotify/id/*"
to = "/netlify/functions/spotify-rss?id=:splat"
