name: Sentry

on:
  push:
    branches:
    - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v3

    - name: Create Sentry Release
      uses: getsentry/action-release@v1
      env:
        SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
        SENTRY_ORG: subtle-software
        SENTRY_PROJECT: omnirss
      with:
        environment: prod
        set_commits: auto
        version: ${{ github.sha }}
