on: [push]
name: Test

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dir:
          - "functions/search"
          - "functions/spotify-rss"
          - "functions/packages/config"
    steps:
      - uses: actions/checkout@v4
      - name: Lint
        run: pushd "${{ matrix.dir }}"; if [ "$(gofmt -s -l . | wc -l)" -gt 0 ]; then exit 1; fi
